In [1]:
import pandas as pd

file_path = "inputs.xlsx"
df = pd.read_excel(file_path)
df

,link,id,fundingSource,institute,isHumanStudy,consentDescription,element_1A
0,https://grants.nih.gov/sites/default/files/flm...,1,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,"Demographic, clinical, and MRI, 1 H fMRS and f..."
1,https://grants.nih.gov/sites/default/files/flm...,2,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,Our genomic study will be registered with dbGa...
2,https://grants.nih.gov/sites/default/files/flm...,3,NIH,National Institute of Mental Health (NIMH),no,no,"As detailed in the Research Strategy Section, ..."
3,https://grants.nih.gov/sites/default/files/flm...,4,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,The data to be shared will include MRI images ...

In [2]:
def build_prompt(row):
    funding_source = str(row.get("fundingSource", "Not provided")).strip()
    institute = str(row.get("institute", "Not provided")).strip()
    is_human = str(row.get("isHumanStudy", "No")).strip()
    consent = str(row.get("consentDescription", "no")).strip()
    data_collected = str(row.get("element_1A", "Not provided")).strip()

    consent_block = ""
    if is_human.lower() in ["yes", "true", "1"]:
        consent_block = f"\n- If yes, data sharing consent: {consent if consent else 'Not provided'}"

    prompt = f"""
You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to {funding_source}, specifically targeting {institute}.

Proposal context:
- Funding source: {funding_source}
- Human subjects study: {is_human}{consent_block}
- Data to be collected: {data_collected}

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1- Suggested file formats for each data type
Identify the recommended file format or formats for each data type in the dataset. Briefly explain why these formats are appropriate for FAIR sharing, reuse, interoperability, and long-term preservation.
2- Tools for converting data to the suggested file formats
List tools, software, or workflows that can be used to convert raw or source data into the recommended file formats.
3- Suggested standard structure to organize the dataset
State the recommended dataset structure, schema, specification, or community standard that should be used to organize the dataset, if one exists.
4- Tools for organizing the dataset in the suggested structure
List tools, software, templates, or platforms that can help organize the dataset according to the recommended structure or standard.
5- Metadata and information that should be provided with the data
Describe the metadata, documentation, contextual information, data dictionaries, codebooks, README files, protocols, and any other supporting information that should accompany the dataset.
6- Suggested standard structure and file format for metadata
State the recommended structure, schema, standard, and file format that should be used for metadata and documentation files included with the dataset.
7-Tools for preparing metadata in the suggested structure and file format
List tools, software, validators, templates, or platforms that can help create, manage, standardize, or validate metadata in the recommended structure and format.
8- Suggested de-identification approach
State whether de-identification is required. Explain the recommended de-identification or privacy-preserving approach based on the subject type, data modality, sensitivity of the data, and whether human participants are involved. If consent language affects sharing, explain that clearly.
9- Tools to implement the suggested de-identification approach
List tools, software, workflows, or methods that can help implement the recommended de-identification or privacy protection approach.
10-Suggested repositories for sharing the dataset
Recommend appropriate repositories for sharing the dataset, prioritizing repositories required, recommended, or commonly accepted by the funding source, subject type, and data modality.
11- Suggested license for sharing the dataset
Recommend an appropriate data license or licensing approach, prioritizing what is expected, suggested, or required by the funding source. If restrictions apply because of human subjects, controlled access, or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as “Recommended approach” and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.
"""
    return prompt.strip()


# Create prompt column
df["prompt"] = df.apply(build_prompt, axis=1)

# Show first prompt
print(df["prompt"].iloc[0])

You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to NIH, specifically targeting National Institute of Mental Health (NIMH).

Proposal context:
- Funding source: NIH
- Human subjects study: yes
- If yes, data sharing consent: All research participants will be consented for broad data sharing.
- Data to be collected: Demographic, clinical, and MRI, 1 H fMRS and fMRI imaging data will be acquired from 110 affected youth and 110 matched healthy controls (described in detail in sections C.3 and C.4 of this application). All data will be deidentified prior to receipt by the repository, but the information needed to generate a global unique identifier for the NIMH Data Archive (NDA) will be collected for each subject.

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1- Suggested file formats for each data type
Identify the recommended file format or formats for each data type in the dataset. Briefly explain why these formats are appropriate for FAIR sharing, reuse, interoperability, and long-term preservation.
2- Tools for converting data to the suggested file formats
List tools, software, or workflows that can be used to convert raw or source data into the recommended file formats.
3- Suggested standard structure to organize the dataset
State the recommended dataset structure, schema, specification, or community standard that should be used to organize the dataset, if one exists.
4- Tools for organizing the dataset in the suggested structure
List tools, software, templates, or platforms that can help organize the dataset according to the recommended structure or standard.
5- Metadata and information that should be provided with the data
Describe the metadata, documentation, contextual information, data dictionaries, codebooks, README files, protocols, and any other supporting information that should accompany the dataset.
6- Suggested standard structure and file format for metadata
State the recommended structure, schema, standard, and file format that should be used for metadata and documentation files included with the dataset.
7-Tools for preparing metadata in the suggested structure and file format
List tools, software, validators, templates, or platforms that can help create, manage, standardize, or validate metadata in the recommended structure and format.
8- Suggested de-identification approach
State whether de-identification is required. Explain the recommended de-identification or privacy-preserving approach based on the subject type, data modality, sensitivity of the data, and whether human participants are involved. If consent language affects sharing, explain that clearly.
9- Tools to implement the suggested de-identification approach
List tools, software, workflows, or methods that can help implement the recommended de-identification or privacy protection approach.
10-Suggested repositories for sharing the dataset
Recommend appropriate repositories for sharing the dataset, prioritizing repositories required, recommended, or commonly accepted by the funding source, subject type, and data modality.
11- Suggested license for sharing the dataset
Recommend an appropriate data license or licensing approach, prioritizing what is expected, suggested, or required by the funding source. If restrictions apply because of human subjects, controlled access, or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as “Recommended approach” and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

In [3]:
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
client = OpenAI()

def ask_gpt(prompt_text):
    response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[
            {
                "role": "system",
                "content": "You are a FAIR data expert helping generate practical FAIR instructions."
            },
            {
                "role": "user",
                "content": prompt_text
            }
        ],
        temperature=0
    )
    return response.choices[0].message.content

# Apply to each row
df["gpt_answer"] = df["prompt"].apply(ask_gpt)

# Save output
df.to_excel("FAIR_instructions_with_prompts_and_answers1.xlsx", index=False)

In [4]:
for i, row in df.iterrows():
    print(f"\n--- Row {i} ---")
    print("PROMPT:\n", row["prompt"])
    print("\nANSWER:\n", row["gpt_answer"])
    print("\n" + "="*60)

--- Row 0 ---
PROMPT:
 You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to NIH, specifically targeting National Institute of Mental Health (NIMH).

Proposal context:
- Funding source: NIH
- Human subjects study: yes
- If yes, data sharing consent: All research participants will be consented for broad data sharing.
- Data to be collected: Demographic, clinical, and MRI, 1 H fMRS and fMRI imaging data will be acquired from 110 affected youth and 110 matched healthy controls (described in detail in sections C.3 and C.4 of this application). All data will be deidentified prior to receipt by the repository, but the information needed to generate a global unique identifier for the NIMH Data Archive (NDA) will be collected for each subject.

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1- Suggested file formats for each data type
Identify the recommended file format or formats for each data type in the dataset. Briefly explain why these formats are appropriate for FAIR sharing, reuse, interoperability, and long-term preservation.
2- Tools for converting data to the suggested file formats
List tools, software, or workflows that can be used to convert raw or source data into the recommended file formats.
3- Suggested standard structure to organize the dataset
State the recommended dataset structure, schema, specification, or community standard that should be used to organize the dataset, if one exists.
4- Tools for organizing the dataset in the suggested structure
List tools, software, templates, or platforms that can help organize the dataset according to the recommended structure or standard.
5- Metadata and information that should be provided with the data
Describe the metadata, documentation, contextual information, data dictionaries, codebooks, README files, protocols, and any other supporting information that should accompany the dataset.
6- Suggested standard structure and file format for metadata
State the recommended structure, schema, standard, and file format that should be used for metadata and documentation files included with the dataset.
7-Tools for preparing metadata in the suggested structure and file format
List tools, software, validators, templates, or platforms that can help create, manage, standardize, or validate metadata in the recommended structure and format.
8- Suggested de-identification approach
State whether de-identification is required. Explain the recommended de-identification or privacy-preserving approach based on the subject type, data modality, sensitivity of the data, and whether human participants are involved. If consent language affects sharing, explain that clearly.
9- Tools to implement the suggested de-identification approach
List tools, software, workflows, or methods that can help implement the recommended de-identification or privacy protection approach.
10-Suggested repositories for sharing the dataset
Recommend appropriate repositories for sharing the dataset, prioritizing repositories required, recommended, or commonly accepted by the funding source, subject type, and data modality.
11- Suggested license for sharing the dataset
Recommend an appropriate data license or licensing approach, prioritizing what is expected, suggested, or required by the funding source. If restrictions apply because of human subjects, controlled access, or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as “Recommended approach” and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

ANSWER:
 Certainly! Below is practical, NIH/NIMH-tailored FAIR data guidance for your grant proposal, based on your study context.

---

## 1. Suggested file formats for each data type

**Demographic & Clinical Data:**
- **Format:** CSV (.csv), TSV (.tsv), or JSON (.json)
- **Rationale:** These are open, non-proprietary, widely supported formats that facilitate interoperability, reuse, and long-term preservation.

**MRI, 1H fMRS, and fMRI Imaging Data:**
- **Format:** NIfTI (.nii or .nii.gz) for image data; DICOM (.dcm) for raw data
- **Rationale:** NIfTI is the community standard for neuroimaging, supported by most analysis tools and repositories. DICOM is the clinical acquisition standard but should be converted to NIfTI for sharing and analysis.

---

## 2. Tools for converting data to the suggested file formats

- **Demographic/Clinical Data:**
  - Microsoft Excel, LibreOffice Calc, R, or Python (pandas) for exporting to CSV/TSV/JSON.
- **Imaging Data:**
  - [dcm2niix](https://github.com/rordenlab/dcm2niix): Converts DICOM to NIfTI.
  - [MRIconvert](https://lcni.uoregon.edu/downloads/mriconvert): Alternative for DICOM to NIfTI conversion.

---

## 3. Suggested standard structure to organize the dataset

- **Recommended Standard:** [BIDS (Brain Imaging Data Structure)](https://bids.neuroimaging.io/)
- **Rationale:** BIDS is the widely adopted community standard for organizing neuroimaging and associated behavioral/clinical data, required by many repositories (including NIMH Data Archive).

---

## 4. Tools for organizing the dataset in the suggested structure

- [BIDS Starter Kit](https://github.com/bids-standard/bids-starter-kit): Templates and guides for BIDS organization.
- [HeuDiConv](https://github.com/nipy/heudiconv): Automated DICOM-to-BIDS conversion.
- [BIDScoin](https://bidscoin.readthedocs.io/): GUI tool for converting and organizing data into BIDS.
- [OpenNeuro BIDS Validator](https://bids-standard.github.io/bids-validator/): Checks dataset compliance with BIDS.

---

## 5. Metadata and information that should be provided with the data

- **README file:** Overview of the dataset, study design, and data collection protocols.
- **Data dictionary/codebook:** Definitions and allowable values for all variables in demographic/clinical data.
- **Dataset description:** Study aims, participant inclusion/exclusion criteria, and data acquisition details.
- **Acquisition protocols:** Detailed MRI/fMRI/fMRS acquisition parameters.
- **Consent documentation:** Template or summary of consent language permitting broad data sharing.
- **Processing scripts:** Any code or workflow used for data preprocessing or analysis.

---

## 6. Suggested standard structure and file format for metadata

- **Structure:** BIDS metadata files (sidecar JSON files for imaging data, dataset_description.json, participants.tsv, etc.)
- **Format:** JSON (.json) for structured metadata; TSV (.tsv) for tabular data.
- **Rationale:** BIDS-compliant metadata ensures interoperability and reusability, and is required by most neuroimaging repositories.

---

## 7. Tools for preparing metadata in the suggested structure and file format

- [BIDS Starter Kit](https://github.com/bids-standard/bids-starter-kit): Metadata templates and examples.
- [BIDS Validator](https://bids-standard.github.io/bids-validator/): Checks metadata completeness and correctness.
- [OpenNeuro Metadata Editor](https://openneuro.org/): Online tool for editing BIDS metadata.
- [BIDScoin](https://bidscoin.readthedocs.io/): Assists with metadata creation during conversion.

---

## 8. Suggested de-identification approach

- **Requirement:** De-identification is required for all human subject data prior to sharing.
- **Approach:**
  - Remove all direct identifiers (names, dates of birth, addresses, etc.).
  - For imaging data, remove facial features from structural scans (defacing).
  - Use the NIMH Data Archive (NDA) Global Unique Identifier (GUID) system to pseudonymize subjects.
  - Retain only the minimum necessary demographic information (e.g., age at scan, sex, race/ethnicity as permitted by consent).
- **Consent:** All participants are consented for broad data sharing, enabling data deposition in controlled-access repositories.

---

## 9. Tools to implement the suggested de-identification approach

- **Imaging Data:**
  - [pydeface](https://github.com/poldracklab/pydeface), [mri_deface](https://surfer.nmr.mgh.harvard.edu/fswiki/mri_deface): For defacing MRI images.
  - [dcm2niix](https://github.com/rordenlab/dcm2niix): Removes DICOM headers with PHI during conversion.
- **Demographic/Clinical Data:**
  - Manual review and scripting (R, Python) to remove identifiers.
- **NDA GUID Tool:**
  - [NDA GUID Tool](https://nda.nih.gov/tools.html): For generating and managing subject GUIDs.

---

## 10. Suggested repositories for sharing the dataset

- **Primary Recommendation:** [NIMH Data Archive (NDA)](https://nda.nih.gov/)
  - **Rationale:** NDA is required for NIMH-funded human subjects research and supports controlled access, GUIDs, and BIDS datasets.
- **Secondary/Complementary:**
  - [OpenNeuro](https://openneuro.org/): For open-access sharing of BIDS-compliant neuroimaging data (if appropriate and permitted by consent).
  - [dbGaP](https://www.ncbi.nlm.nih.gov/gap): For genetic or sensitive clinical data, if applicable.

---

## 11. Suggested license for sharing the dataset

- **Recommended License:**
  - **NDA:** Data are shared under NDA’s Data Use Certification Agreement, which provides controlled access and requires users to agree to terms of use.
  - **OpenNeuro (if used):** [CC0 1.0 Universal (Public Domain Dedication)](https://creativecommons.org/publicdomain/zero/1.0/) is the default, but only if permitted by consent and IRB.
- **Restrictions:**
  - Because data are from human subjects, sharing must comply with participant consent, IRB approval, and repository access controls. Broad sharing is permitted per your consent language, but controlled access via NDA is required by NIMH.

---

**Summary:**
By following these recommendations—using open, community-accepted formats (CSV, NIfTI, BIDS), robust de-identification, comprehensive metadata, and depositing in the NIMH Data Archive with appropriate licensing—you will maximize the FAIRness, impact, and compliance of your dataset.

============================================================

--- Row 1 ---
PROMPT:
 You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to NIH, specifically targeting National Institute of Mental Health (NIMH).

Proposal context:
- Funding source: NIH
- Human subjects study: yes
- If yes, data sharing consent: All research participants will be consented for broad data sharing.
- Data to be collected: Our genomic study will be registered with dbGaP, and our raw whole genome sequencing data and derived data
 will be submitted to the NIMH Data Archive (NDA). Phenotypic and clinical data for all 500 research subjects will
 be collected and deposited in NDA using the data dictionaries available in NDA (described below).

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1- Suggested file formats for each data type
Identify the recommended file format or formats for each data type in the dataset. Briefly explain why these formats are appropriate for FAIR sharing, reuse, interoperability, and long-term preservation.
2- Tools for converting data to the suggested file formats
List tools, software, or workflows that can be used to convert raw or source data into the recommended file formats.
3- Suggested standard structure to organize the dataset
State the recommended dataset structure, schema, specification, or community standard that should be used to organize the dataset, if one exists.
4- Tools for organizing the dataset in the suggested structure
List tools, software, templates, or platforms that can help organize the dataset according to the recommended structure or standard.
5- Metadata and information that should be provided with the data
Describe the metadata, documentation, contextual information, data dictionaries, codebooks, README files, protocols, and any other supporting information that should accompany the dataset.
6- Suggested standard structure and file format for metadata
State the recommended structure, schema, standard, and file format that should be used for metadata and documentation files included with the dataset.
7-Tools for preparing metadata in the suggested structure and file format
List tools, software, validators, templates, or platforms that can help create, manage, standardize, or validate metadata in the recommended structure and format.
8- Suggested de-identification approach
State whether de-identification is required. Explain the recommended de-identification or privacy-preserving approach based on the subject type, data modality, sensitivity of the data, and whether human participants are involved. If consent language affects sharing, explain that clearly.
9- Tools to implement the suggested de-identification approach
List tools, software, workflows, or methods that can help implement the recommended de-identification or privacy protection approach.
10-Suggested repositories for sharing the dataset
Recommend appropriate repositories for sharing the dataset, prioritizing repositories required, recommended, or commonly accepted by the funding source, subject type, and data modality.
11- Suggested license for sharing the dataset
Recommend an appropriate data license or licensing approach, prioritizing what is expected, suggested, or required by the funding source. If restrictions apply because of human subjects, controlled access, or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as “Recommended approach” and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

ANSWER:
 Certainly! Below is practical, NIH/NIMH-tailored FAIR data guidance for your human subjects genomic study, organized by the requested sections.

---

### 1. Suggested file formats for each data type

**a. Raw Whole Genome Sequencing Data:**
- **Format:** FASTQ (raw reads), BAM/CRAM (aligned reads), VCF (variant calls)
- **Rationale:** These are community-standard, open formats widely supported by genomics tools and repositories. They ensure interoperability, long-term preservation, and broad reuse.

**b. Derived Genomic Data (e.g., variant annotations):**
- **Format:** VCF (for variants), TSV/CSV (for tabular annotations)
- **Rationale:** VCF is the standard for variant data; TSV/CSV are open, machine-readable, and widely supported.

**c. Phenotypic and Clinical Data:**
- **Format:** CSV/TSV (tabular data), following NDA data dictionary templates
- **Rationale:** CSV/TSV are open, non-proprietary, and compatible with NDA requirements.

**d. Metadata and Documentation:**
- **Format:** JSON, XML, or CSV (for structured metadata); PDF or TXT (for protocols, README)
- **Rationale:** JSON/XML are machine-readable and align with NDA and dbGaP metadata standards; PDF/TXT are accessible for human-readable documentation.

---

### 2. Tools for converting data to the suggested file formats

- **FASTQ/BAM/CRAM/VCF:**
  - [samtools](http://www.htslib.org/), [bcftools](http://www.htslib.org/), [GATK](https://gatk.broadinstitute.org/), [Picard](https://broadinstitute.github.io/picard/)
- **CSV/TSV:**
  - Microsoft Excel, LibreOffice Calc, R, Python (pandas), NDA Data Dictionary Templates
- **JSON/XML:**
  - R, Python, [OpenRefine](https://openrefine.org/), NDA Data Dictionary Tools
- **PDF/TXT:**
  - Microsoft Word, Google Docs, LaTeX, Notepad

---

### 3. Suggested standard structure to organize the dataset

- **Genomic Data:**
  - Organize by subject/sample ID, with subfolders for raw (FASTQ), aligned (BAM/CRAM), and variant (VCF) files.
- **Phenotypic/Clinical Data:**
  - Use NDA data dictionary structure: one row per subject, columns as per NDA variable definitions.
- **Metadata/Documentation:**
  - Include a top-level `README.txt`, data dictionaries, and protocol files.
- **Recommended Standard:**
  - Follow the [NIMH Data Archive (NDA) Submission Structure](https://nda.nih.gov/nda/tools/submission.html) and [dbGaP Submission Guidelines](https://www.ncbi.nlm.nih.gov/gap/docs/submissionguide/).

---

### 4. Tools for organizing the dataset in the suggested structure

- **NDA Data Submission Tool** (for uploading and structuring data per NDA requirements)
- **dbGaP Submission Portal** (for genomic data registration)
- **NDA Data Dictionary Templates** (Excel/CSV templates)
- **File organization scripts** (custom scripts in Python/R for file/folder management)

---

### 5. Metadata and information that should be provided with the data

- **Project-level metadata:** Study title, abstract, PI, funding source, IRB protocol, consent language
- **Subject/sample metadata:** Unique IDs, demographic variables, consent group, collection site
- **Data dictionaries:** Definitions, permissible values, units for each variable (use NDA templates)
- **README file:** Overview of dataset structure, file descriptions, processing steps, contact info
- **Protocols:** Detailed methods for sample collection, sequencing, data processing, QC
- **Data provenance:** Software versions, pipeline parameters, date of data generation

---

### 6. Suggested standard structure and file format for metadata

- **Structure:**
  - Use the [NDA Data Dictionary](https://nda.nih.gov/nda/data-dictionary.html) for phenotypic/clinical data
  - Use [dbGaP metadata templates](https://www.ncbi.nlm.nih.gov/gap/docs/submissionguide/#metadata) for genomic data
- **File formats:**
  - CSV/TSV for data dictionaries
  - JSON/XML for structured metadata (if required by repository)
  - PDF/TXT for protocols and README

---

### 7. Tools for preparing metadata in the suggested structure and file format

- **NDA Data Dictionary Tool** (Excel/CSV templates and online validator)
- **dbGaP Submission Portal** (metadata templates and validation)
- **OpenRefine** (for cleaning and standardizing tabular metadata)
- **R/Python scripts** (for generating JSON/XML metadata)
- **NDA Validator** (for checking compliance with NDA requirements)

---

### 8. Suggested de-identification approach

- **De-identification is required** for all human subjects data prior to sharing.
- **Recommended approach:**
  - Remove all direct identifiers (names, addresses, contact info, etc.)
  - Replace subject IDs with NDA Global Unique Identifiers (GUIDs)
  - Generalize or bin sensitive indirect identifiers (e.g., age as age group)
  - For genomic data, follow dbGaP/NDA guidelines for controlled-access and privacy protection
- **Consent language:**
  - As all participants are consented for broad data sharing, data can be shared under controlled access, but must still be de-identified per NIH policy.

---

### 9. Tools to implement the suggested de-identification approach


# Another prompt version

In [6]:
import json
import pandas as pd

def build_prompt(row):
    funding_source = str(row.get("fundingSource", "Not provided")).strip()
    institute = str(row.get("institute", "Not provided")).strip()
    is_human = str(row.get("isHumanStudy", "No")).strip()
    consent = str(row.get("consentDescription", "no")).strip()
    data_collected = str(row.get("element_1A", "Not provided")).strip()

    consent_block = ""
    if is_human.lower() in ["yes", "true", "1"]:
        consent_block = f"\n- If yes, data sharing consent: {consent if consent else 'Not provided'}"

    prompt = f"""
You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to {funding_source}, specifically targeting {institute}.

Proposal context:
- Funding source: {funding_source}
- Human subjects study: {is_human}{consent_block}
- Data to be collected: {data_collected}

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1- Suggested file formats for each data type
Identify the recommended file format or formats for each data type in the dataset. Briefly explain why these formats are appropriate for FAIR sharing, reuse, interoperability, and long-term preservation.
2- Tools for converting data to the suggested file formats
List tools, software, or workflows that can be used to convert raw or source data into the recommended file formats.
3- Suggested standard structure to organize the dataset
State the recommended dataset structure, schema, specification, or community standard that should be used to organize the dataset, if one exists.
4- Tools for organizing the dataset in the suggested structure
List tools, software, templates, or platforms that can help organize the dataset according to the recommended structure or standard.
5- Metadata and information that should be provided with the data
Describe the metadata, documentation, contextual information, data dictionaries, codebooks, README files, protocols, and any other supporting information that should accompany the dataset.
6- Suggested standard structure and file format for metadata
State the recommended structure, schema, standard, and file format that should be used for metadata and documentation files included with the dataset.
7-Tools for preparing metadata in the suggested structure and file format
List tools, software, validators, templates, or platforms that can help create, manage, standardize, or validate metadata in the recommended structure and format.
8- Suggested de-identification approach
State whether de-identification is required. Explain the recommended de-identification or privacy-preserving approach based on the subject type, data modality, sensitivity of the data, and whether human participants are involved. If consent language affects sharing, explain that clearly.
9- Tools to implement the suggested de-identification approach
List tools, software, workflows, or methods that can help implement the recommended de-identification or privacy protection approach.
10-Suggested repositories for sharing the dataset
Recommend appropriate repositories for sharing the dataset, prioritizing repositories required, recommended, or commonly accepted by the funding source, subject type, and data modality.
11- Suggested license for sharing the dataset
Recommend an appropriate data license or licensing approach, prioritizing what is expected, suggested, or required by the funding source. If restrictions apply because of human subjects, controlled access, or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as "Recommended approach" and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

Return your answer in valid JSON format only.


Use exactly this JSON structure:
{{
  "1-Suggested file formats for each data type": "",
  "2-Tools for converting data to the suggested file formats": "",
  "3-Suggested standard structure to organize the dataset": "",
  "4-Tools for organizing the dataset in the suggested structure": "",
  "5-Metadata and information that should be provided with the data": "",
  "6-Suggested standard structure and file format for metadata": "",
  "7-Tools for preparing metadata in the suggested structure and file format": "",
  "8-Suggested de-identification approach": "",
  "9-Tools to implement the suggested de-identification approach": "",
  "10-Suggested repositories for sharing the dataset": "",
  "11-Suggested license for sharing the dataset": ""
}}
"""
    return prompt.strip()


# Create prompt column
df["prompt"] = df.apply(build_prompt, axis=1)

# Show first prompt
print(df["prompt"].iloc[0])

You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to NIH, specifically targeting National Institute of Mental Health (NIMH).

Proposal context:
- Funding source: NIH
- Human subjects study: yes
- If yes, data sharing consent: All research participants will be consented for broad data sharing.
- Data to be collected: Demographic, clinical, and MRI, 1 H fMRS and fMRI imaging data will be acquired from 110 affected youth and 110 matched healthy controls (described in detail in sections C.3 and C.4 of this application). All data will be deidentified prior to receipt by the repository, but the information needed to generate a global unique identifier for the NIMH Data Archive (NDA) will be collected for each subject.

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1- Suggested file formats for each data type
Identify the recommended file format or formats for each data type in the dataset. Briefly explain why these formats are appropriate for FAIR sharing, reuse, interoperability, and long-term preservation.
2- Tools for converting data to the suggested file formats
List tools, software, or workflows that can be used to convert raw or source data into the recommended file formats.
3- Suggested standard structure to organize the dataset
State the recommended dataset structure, schema, specification, or community standard that should be used to organize the dataset, if one exists.
4- Tools for organizing the dataset in the suggested structure
List tools, software, templates, or platforms that can help organize the dataset according to the recommended structure or standard.
5- Metadata and information that should be provided with the data
Describe the metadata, documentation, contextual information, data dictionaries, codebooks, README files, protocols, and any other supporting information that should accompany the dataset.
6- Suggested standard structure and file format for metadata
State the recommended structure, schema, standard, and file format that should be used for metadata and documentation files included with the dataset.
7-Tools for preparing metadata in the suggested structure and file format
List tools, software, validators, templates, or platforms that can help create, manage, standardize, or validate metadata in the recommended structure and format.
8- Suggested de-identification approach
State whether de-identification is required. Explain the recommended de-identification or privacy-preserving approach based on the subject type, data modality, sensitivity of the data, and whether human participants are involved. If consent language affects sharing, explain that clearly.
9- Tools to implement the suggested de-identification approach
List tools, software, workflows, or methods that can help implement the recommended de-identification or privacy protection approach.
10-Suggested repositories for sharing the dataset
Recommend appropriate repositories for sharing the dataset, prioritizing repositories required, recommended, or commonly accepted by the funding source, subject type, and data modality.
11- Suggested license for sharing the dataset
Recommend an appropriate data license or licensing approach, prioritizing what is expected, suggested, or required by the funding source. If restrictions apply because of human subjects, controlled access, or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as "Recommended approach" and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

Return your answer in valid JSON format only.


Use exactly this JSON structure:
{
  "1-Suggested file formats for each data type": "",
  "2-Tools for converting data to the suggested file formats": "",
  "3-Suggested standard structure to organize the dataset": "",
  "4-Tools for organizing the dataset in the suggested structure": "",
  "5-Metadata and information that should be provided with the data": "",
  "6-Suggested standard structure and file format for metadata": "",
  "7-Tools for preparing metadata in the suggested structure and file format": "",
  "8-Suggested de-identification approach": "",
  "9-Tools to implement the suggested de-identification approach": "",
  "10-Suggested repositories for sharing the dataset": "",
  "11-Suggested license for sharing the dataset": ""
}

In [7]:
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
client = OpenAI()

def ask_gpt(prompt_text):
    response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[
            {
                "role": "system",
                "content": "You are a FAIR data expert helping generate practical FAIR instructions."
            },
            {
                "role": "user",
                "content": prompt_text
            }
        ],
        temperature=0
    )
    return response.choices[0].message.content

# Apply to each row
df["gpt_answer"] = df["prompt"].apply(ask_gpt)

# Save output
df.to_excel("FAIR_instructions_with_prompts_and_answers2.xlsx", index=False)

In [8]:
import json
import re
import pandas as pd

def parse_json_result(text):
    empty_result = {
  "1-Suggested file formats for each data type": "",
  "2-Tools for converting data to the suggested file formats": "",
  "3-Suggested standard structure to organize the dataset": "",
  "4-Tools for organizing the dataset in the suggested structure": "",
  "5-Metadata and information that should be provided with the data": "",
  "6-Suggested standard structure and file format for metadata": "",
  "7-Tools for preparing metadata in the suggested structure and file format": "",
  "8-Suggested de-identification approach": "",
  "9-Tools to implement the suggested de-identification approach": "",
  "10-Suggested repositories for sharing the dataset": "",
  "11-Suggested license for sharing the dataset": ""
}

    try:
        if pd.isna(text):
            return pd.Series(empty_result)

        text = str(text).strip()

        # If GPT added extra text before/after JSON, extract only the JSON part
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            text = match.group(0)

        data = json.loads(text)

        return pd.Series({
            "1-Suggested file formats for each data type": data.get("1-Suggested file formats for each data type", ""),
            "2-Tools for converting data to the suggested file formats": data.get("2-Tools for converting data to the suggested file formats", ""),
            "3-Suggested standard structure to organize the dataset": data.get("3-Suggested standard structure to organize the dataset", ""),
            "4-Tools for organizing the dataset in the suggested structure": data.get("4-Tools for organizing the dataset in the suggested structure", ""),
            "5-Metadata and information that should be provided with the data": data.get("5-Metadata and information that should be provided with the data", ""),
            "6-Suggested standard structure and file format for metadata": data.get("6-Suggested standard structure and file format for metadata", ""),
            "7-Tools for preparing metadata in the suggested structure and file format": data.get("7-Tools for preparing metadata in the suggested structure and file format", ""),
            "8-Suggested de-identification approach": data.get("8-Suggested de-identification approach", ""),
            "9-Tools to implement the suggested de-identification approach": data.get("9-Tools to implement the suggested de-identification approach", ""),
            "10-Suggested repositories for sharing the dataset": data.get("10-Suggested repositories for sharing the dataset", ""),
            "11-Suggested license for sharing the dataset": data.get("11-Suggested license for sharing the dataset", "")
        })

    except Exception:
        return pd.Series(empty_result)


# Keep only your original columns first
base_cols = [
    "link",
    "id",
    "fundingSource",
    "institute",
    "isHumanStudy",
    "consentDescription",
    "element_1A",
    "prompt",
    "gpt_answer"
]

df_base = df[base_cols].copy()

# Parse JSON from gpt_answer
parsed_cols = df_base["gpt_answer"].apply(parse_json_result)

# Combine original columns + parsed columns only once
df_clean = pd.concat([df_base, parsed_cols], axis=1)

# Preview selected columns
print(df_clean[[
    "1-Suggested file formats for each data type",
    "2-Tools for converting data to the suggested file formats",
    "3-Suggested standard structure to organize the dataset"
]].head())

# Save clean file
df_clean.to_excel("FAIR_instructions_with_parsed_columns.xlsx", index=False)

         1-Suggested file formats for each data type  \
0  {'Demographic and Clinical Data': 'CSV (Comma-...
1  {'Genomic raw data': 'FASTQ (raw reads), BAM/C...
2  For single-cell matrices (ATAC, RNA, DNAm): us...
3  {'MRI images': 'NIfTI (.nii or .nii.gz) is rec...

  2-Tools for converting data to the suggested file formats  \
0  {'Demographic and Clinical Data': 'Microsoft E...
1  {'Genomic data': 'bcl2fastq (Illumina), samtoo...
2  Seurat (R), Scanpy (Python), and Bioconductor ...
3  {'MRI images': 'dcm2niix is a widely used tool...

  3-Suggested standard structure to organize the dataset
0  BIDS (Brain Imaging Data Structure) is the rec...
1  Follow the NIMH Data Archive (NDA) data struct...
2  Recommended approach: Use the Human Cell Atlas...
3  The Brain Imaging Data Structure (BIDS) is the...

In [9]:
df_clean

,link,id,fundingSource,institute,isHumanStudy,consentDescription,element_1A,prompt,gpt_answer,1-Suggested file formats for each data type,2-Tools for converting data to the suggested file formats,3-Suggested standard structure to organize the dataset,4-Tools for organizing the dataset in the suggested structure,5-Metadata and information that should be provided with the data,6-Suggested standard structure and file format for metadata,7-Tools for preparing metadata in the suggested structure and file format,8-Suggested de-identification approach,9-Tools to implement the suggested de-identification approach,10-Suggested repositories for sharing the dataset,11-Suggested license for sharing the dataset
0,https://grants.nih.gov/sites/default/files/flm...,1,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,"Demographic, clinical, and MRI, 1 H fMRS and f...",You are a FAIR data expert helping researchers...,"{\n ""1-Suggested file formats for each data t...",{'Demographic and Clinical Data': 'CSV (Comma-...,{'Demographic and Clinical Data': 'Microsoft E...,BIDS (Brain Imaging Data Structure) is the rec...,"BIDS Starter Kit, HeuDiConv, bidskit, and the ...",Comprehensive metadata should include: (1) Dat...,BIDS-compliant JSON files for imaging metadata...,"BIDS Validator (web or command-line), BIDS Sta...",De-identification is required for all human su...,pydeface or mri_deface for defacing MRI images...,The NIMH Data Archive (NDA) is the required re...,Data shared via NDA is subject to NDA's Data U...
1,https://grants.nih.gov/sites/default/files/flm...,2,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,Our genomic study will be registered with dbGa...,You are a FAIR data expert helping researchers...,"{\n ""1-Suggested file formats for each data t...","{'Genomic raw data': 'FASTQ (raw reads), BAM/C...","{'Genomic data': 'bcl2fastq (Illumina), samtoo...",Follow the NIMH Data Archive (NDA) data struct...,"NDA Data Submission Tool (NDA Upload Tool), ND...",Comprehensive metadata including study descrip...,NDA requires metadata in their standardized da...,"NDA Data Dictionary Tool, NDA web-based metada...",De-identification is required for all human su...,NDA GUID Tool for generating subject identifie...,Raw and processed genomic data: dbGaP (require...,Data should be shared under controlled access ...
2,https://grants.nih.gov/sites/default/files/flm...,3,NIH,National Institute of Mental Health (NIMH),no,no,"As detailed in the Research Strategy Section, ...",You are a FAIR data expert helping researchers...,"{\n ""1-Suggested file formats for each data t...","For single-cell matrices (ATAC, RNA, DNAm): us...","Seurat (R), Scanpy (Python), and Bioconductor ...",Recommended approach: Use the Human Cell Atlas...,The HCA Data Coordination Platform (DCP) tools...,Provide a comprehensive README file describing...,Recommended approach: Use the Minimum Informat...,"HCA metadata submission tools, DataCite Metada...",De-identification is not required for mouse da...,"For mouse data, no de-identification tools are...","For mouse single-cell omics data, deposit in t...",Recommended approach: Use the Creative Commons...
3,https://grants.nih.gov/sites/default/files/flm...,4,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,The data to be shared will include MRI images ...,You are a FAIR data expert helping researchers...,"{\n ""1-Suggested file formats for each data t...",{'MRI images': 'NIfTI (.nii or .nii.gz) is rec...,{'MRI images': 'dcm2niix is a widely used tool...,The Brain Imaging Data Structure (BIDS) is the...,"BIDS Starter Kit (templates and guides), BIDSc...",Provide a comprehensive README file describing...,"Use the BIDS metadata structure, which include...","BIDS Starter Kit (metadata templates), BIDS Va...",De-identification is required for all human su...,"For MRI: pydeface, mri_deface, or FSL's deface...",The NIMH Data Archive (NDA) is the required re...,NDA requires data to be shared under a control...

In [10]:
print(len(df_clean.columns))
print(df_clean.columns.tolist())

20
['link', 'id', 'fundingSource', 'institute', 'isHumanStudy', 'consentDescription', 'element_1A', 'prompt', 'gpt_answer', '1-Suggested file formats for each data type', '2-Tools for converting data to the suggested file formats', '3-Suggested standard structure to organize the dataset', '4-Tools for organizing the dataset in the suggested structure', '5-Metadata and information that should be provided with the data', '6-Suggested standard structure and file format for metadata', '7-Tools for preparing metadata in the suggested structure and file format', '8-Suggested de-identification approach', '9-Tools to implement the suggested de-identification approach', '10-Suggested repositories for sharing the dataset', '11-Suggested license for sharing the dataset']