In [4]:
import pandas as pd

file_path = "inputs.xlsx"
df = pd.read_excel(file_path)
df

,link,id,fundingSource,institute,isHumanStudy,consentDescription,element_1A
0,https://grants.nih.gov/sites/default/files/flm...,1,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,"Demographic, clinical, and MRI, 1 H fMRS and f..."
1,https://grants.nih.gov/sites/default/files/flm...,2,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,Our genomic study will be registered with dbGa...
2,https://grants.nih.gov/sites/default/files/flm...,3,NIH,National Institute of Mental Health (NIMH),no,no,"As detailed in the Research Strategy Section, ..."
3,https://grants.nih.gov/sites/default/files/flm...,4,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,The data to be shared will include MRI images ...

In [ ]:
def build_prompt(row):
    funding_source = str(row.get("fundingSource", "Not provided")).strip()
    institute = str(row.get("institute", "Not provided")).strip()
    is_human = str(row.get("isHumanStudy", "No")).strip()
    consent = str(row.get("consentDescription", "no")).strip()
    data_collected = str(row.get("element_1A", "Not provided")).strip()

    consent_block = ""
    if is_human.lower() in ["yes", "true", "1"]:
        consent_block = f"\n- If yes, data sharing consent: {consent if consent else 'Not provided'}"

    prompt = f"""
You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to {funding_source}, specifically targeting {institute}.

Proposal context:
- Funding source: {funding_source}
- Human subjects study: {is_human}{consent_block}
- Data to be collected: {data_collected}

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1. Recommended file formats  
Explain which file format(s) should be used for this type of data and why they are appropriate for FAIR sharing and reuse.

2. Relevant tools and software  
List tools, software, or platforms that can help prepare, convert, validate, organize, document, or share this type of data.

3. Recommended dataset structure or standard  
State the dataset structure, schema, or community standard that should be followed, if one exists.

4. Dataset organization details  
Provide detailed guidance on how the dataset should be organized, including folder structure, file naming conventions, table organization, metadata arrangement, versioning considerations, and any other important technical details.

5. Metadata and documentation files to include  
List the metadata files, README files, data dictionaries, codebooks, protocols, or other documentation that should accompany the dataset.

6. Tools for metadata preparation and validation  
Suggest tools that can help create, validate, manage, or standardize metadata for this dataset.

7. De-identification and privacy considerations  
State whether de-identification is required. Explain what should be done based on the subject type, the data modality, and whether the study involves human participants. If consent language affects sharing, explain that clearly.

8. Recommended repositories  
Suggest appropriate repositories for sharing the data, prioritizing repositories recommended, required, or commonly accepted by the funding source and data type.

9. Recommended data licenses  
Recommend appropriate data license(s), prioritizing those expected, suggested, or required by the funding source. If restrictions apply because of human subjects or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as “Recommended approach” and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.
"""
    return prompt.strip()


# Create prompt column
df["prompt"] = df.apply(build_prompt, axis=1)

# Show first prompt
print(df["prompt"].iloc[0])

You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to NIH, specifically targeting National Institute of Mental Health (NIMH).

Proposal context:
- Funding source: NIH
- Human subjects study: yes
- If yes, data sharing consent: All research participants will be consented for broad data sharing.
- Data to be collected: Demographic, clinical, and MRI, 1 H fMRS and fMRI imaging data will be acquired from 110 affected youth and 110 matched healthy controls (described in detail in sections C.3 and C.4 of this application). All data will be deidentified prior to receipt by the repository, but the information needed to generate a global unique identifier for the NIMH Data Archive (NDA) will be collected for each subject.

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1. Recommended file formats
Explain which file format(s) should be used for this type of data and why they are appropriate for FAIR sharing and reuse.

2. Relevant tools and software
List tools, software, or platforms that can help prepare, convert, validate, organize, document, or share this type of data.

3. Recommended dataset structure or standard
State the dataset structure, schema, or community standard that should be followed, if one exists.

4. Dataset organization details
Provide detailed guidance on how the dataset should be organized, including folder structure, file naming conventions, table organization, metadata arrangement, versioning considerations, and any other important technical details.

5. Metadata and documentation files to include
List the metadata files, README files, data dictionaries, codebooks, protocols, or other documentation that should accompany the dataset.

6. Tools for metadata preparation and validation
Suggest tools that can help create, validate, manage, or standardize metadata for this dataset.

7. De-identification and privacy considerations
State whether de-identification is required. Explain what should be done based on the subject type, the data modality, and whether the study involves human participants. If consent language affects sharing, explain that clearly.

8. Recommended repositories
Suggest appropriate repositories for sharing the data, prioritizing repositories recommended, required, or commonly accepted by the funding source and data type.

9. Recommended data licenses
Recommend appropriate data license(s), prioritizing those expected, suggested, or required by the funding source. If restrictions apply because of human subjects or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as “Recommended approach” and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

In [ ]:
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
client = OpenAI()

def ask_gpt(prompt_text):
    response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[
            {
                "role": "system",
                "content": "You are a FAIR data expert helping generate practical FAIR instructions."
            },
            {
                "role": "user",
                "content": prompt_text
            }
        ],
        temperature=0
    )
    return response.choices[0].message.content

# Apply to each row
df["gpt_answer"] = df["prompt"].apply(ask_gpt)

# Save output
df.to_excel("FAIR_instructions_with_prompts_and_answers1.xlsx", index=False)

In [7]:
for i, row in df.iterrows():
    print(f"\n--- Row {i} ---")
    print("PROMPT:\n", row["prompt"])
    print("\nANSWER:\n", row["gpt_answer"])
    print("\n" + "="*60)

--- Row 0 ---
PROMPT:
 You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to NIH, specifically targeting National Institute of Mental Health (NIMH).

Proposal context:
- Funding source: NIH
- Human subjects study: yes
- If yes, data sharing consent: All research participants will be consented for broad data sharing.
- Data to be collected: Demographic, clinical, and MRI, 1 H fMRS and fMRI imaging data will be acquired from 110 affected youth and 110 matched healthy controls (described in detail in sections C.3 and C.4 of this application). All data will be deidentified prior to receipt by the repository, but the information needed to generate a global unique identifier for the NIMH Data Archive (NDA) will be collected for each subject.

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1. Recommended file formats
Explain which file format(s) should be used for this type of data and why they are appropriate for FAIR sharing and reuse.

2. Relevant tools and software
List tools, software, or platforms that can help prepare, convert, validate, organize, document, or share this type of data.

3. Recommended dataset structure or standard
State the dataset structure, schema, or community standard that should be followed, if one exists.

4. Dataset organization details
Provide detailed guidance on how the dataset should be organized, including folder structure, file naming conventions, table organization, metadata arrangement, versioning considerations, and any other important technical details.

5. Metadata and documentation files to include
List the metadata files, README files, data dictionaries, codebooks, protocols, or other documentation that should accompany the dataset.

6. Tools for metadata preparation and validation
Suggest tools that can help create, validate, manage, or standardize metadata for this dataset.

7. De-identification and privacy considerations
State whether de-identification is required. Explain what should be done based on the subject type, the data modality, and whether the study involves human participants. If consent language affects sharing, explain that clearly.

8. Recommended repositories
Suggest appropriate repositories for sharing the data, prioritizing repositories recommended, required, or commonly accepted by the funding source and data type.

9. Recommended data licenses
Recommend appropriate data license(s), prioritizing those expected, suggested, or required by the funding source. If restrictions apply because of human subjects or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as “Recommended approach” and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

ANSWER:
 **FAIR Data Guidance for NIH/NIMH Human Subjects Imaging Study**

---

### 1. Recommended File Formats

- **Demographic & Clinical Data:**
  Use **CSV** (Comma-Separated Values) or **TSV** (Tab-Separated Values) for tabular data. These are open, non-proprietary, and widely supported formats that facilitate reuse and interoperability.
- **MRI, fMRI, and 1H fMRS Imaging Data:**
  Use **NIfTI (.nii or .nii.gz)** for MRI and fMRI data. For raw scanner data, **DICOM** is acceptable, but NIfTI is preferred for sharing and analysis.
  For spectroscopy (fMRS), use **NIfTI-MRS** or **vendor-neutral formats** (e.g., LCModel .RAW, .SDAT, or .SPAR), with conversion to NIfTI-MRS if possible.
- **Documentation & Metadata:**
  Use **PDF** or **Markdown (.md)** for protocols and README files. Use **JSON** or **TSV** for structured metadata (e.g., BIDS sidecar files).

---

### 2. Relevant Tools and Software

- **Data Conversion & Organization:**
  - [dcm2niix](https://github.com/rordenlab/dcm2niix): DICOM to NIfTI conversion
  - [BIDScoin](https://bidscoin.readthedocs.io/): Automated BIDS conversion
  - [HeuDiConv](https://heudiconv.readthedocs.io/): DICOM to BIDS conversion
- **Validation:**
  - [BIDS Validator](https://bids-standard.github.io/bids-validator/): Checks BIDS compliance
  - [NDA Validation Tools](https://nda.nih.gov/nda/tools/): For NDA-specific requirements
- **Data Management:**
  - [REDCap](https://www.project-redcap.org/): For clinical/demographic data collection
  - [OpenRefine](https://openrefine.org/): Data cleaning and standardization

---

### 3. Recommended Dataset Structure or Standard

- **Imaging Data:**
  Follow the **Brain Imaging Data Structure (BIDS)** standard (https://bids.neuroimaging.io/), including BIDS extensions for fMRI and MRS data.
- **Clinical/Demographic Data:**
  Organize as BIDS-compliant tabular files (e.g., `participants.tsv`, `phenotype/` folder).
- **Metadata:**
  Use BIDS sidecar JSON files for imaging metadata and NDA-required data dictionaries for tabular data.

---

### 4. Dataset Organization Details

- **Folder Structure:**
  ```
  /project_root/
      /sub-<participant_label>/
          /anat/         # Structural MRI
          /func/         # fMRI
          /mrs/          # fMRS
      /phenotype/        # Clinical/demographic data
      participants.tsv   # Participant-level summary
      dataset_description.json  # BIDS metadata
      README.md
      CHANGES.md         # Version history
      /code/             # Analysis scripts (if applicable)
  ```
- **File Naming Conventions:**
  Use BIDS conventions: `sub-<participant_label>_ses-<session>_task-<task>_modality.nii.gz`
- **Table Organization:**
  - `participants.tsv`: One row per subject, columns for age, sex, group, etc.
  - Data dictionaries: Define each variable, units, and allowed values.
- **Metadata Arrangement:**
  - BIDS sidecar JSON files for each imaging file.
  - NDA-specific data dictionaries and manifest files as required.
- **Versioning:**
  - Maintain a `CHANGES.md` file.
  - Use versioned folder names or tags for major dataset updates.

---

### 5. Metadata and Documentation Files to Include

- **README.md:** Overview of dataset, study design, and file organization.
- **dataset_description.json:** BIDS-required metadata (title, authors, funding, references).
- **participants.tsv:** Participant-level data.
- **Data Dictionary:** Defines all variables in tabular data.
- **Protocol Documents:** Study protocol, consent forms (de-identified), and data collection instruments.
- **CHANGES.md:** Version history.
- **NDA Submission Files:** As required by the NIMH Data Archive (e.g., manifest, data dictionary).

---

### 6. Tools for Metadata Preparation and Validation

- **BIDS Validator:** For checking BIDS compliance.
- **NDA Data Dictionary Tool:** For preparing NDA-compliant data dictionaries.
- **OpenRefine:** For cleaning and standardizing tabular metadata.
- **BIDS Starter Kit:** Templates and guidance for BIDS metadata.

---

### 7. De-identification and Privacy Considerations

- **De-identification is required** for all human subjects data prior to sharing.
- **Imaging Data:**
  - Remove all facial features from structural MRI (defacing tools: [pydeface](https://github.com/poldracklab/pydeface), [mri_deface](https://surfer.nmr.mgh.harvard.edu/fswiki/mri_deface)).
  - Strip all personal identifiers from DICOM headers.
- **Tabular Data:**
  - Remove direct identifiers (names, dates of birth, addresses, etc.).
  - Use NDA Global Unique Identifier (GUID) for subject linkage.
- **Consent:**
  - All participants are consented for broad data sharing, enabling deposition in open or controlled-access repositories as required by NIH/NIMH.
- **Documentation:**
  - Document de-identification procedures in the README or a dedicated file.

---

### 8. Recommended Repositories

- **Primary:**
  - **NIMH Data Archive (NDA):** Required for NIMH-funded human subjects data (https://nda.nih.gov/).
- **Secondary (if allowed by NDA and consent):**
  - **OpenNeuro:** For BIDS-compliant imaging datasets (https://openneuro.org/).
  - **Other NIH-supported repositories** as appropriate for specific data types.

---

### 9. Recommended Data Licenses

- **NDA:**
  - Data shared via NDA is governed by NDA’s Data Use Certification and access controls. No separate license is required; NDA policies apply.
- **Open Repositories (if used):**
  - Use **CC BY 4.0** (Creative Commons Attribution) or **CC0** (public domain dedication) for de-identified data, unless participant consent or NDA policy restricts this.
- **Human Subjects Considerations:**
  - Since broad sharing consent is obtained, open licenses are generally permissible, but always ensure compliance with NDA and NIH policies.

---

**Summary:**
By following these recommendations—using open formats, BIDS structure, robust metadata, NDA submission requirements, and appropriate de-identification—your dataset will be well-aligned with FAIR principles and NIH/NIMH expectations for human subjects imaging research.

============================================================

--- Row 1 ---
PROMPT:
 You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to NIH, specifically targeting National Institute of Mental Health (NIMH).

Proposal context:
- Funding source: NIH
- Human subjects study: yes
- If yes, data sharing consent: All research participants will be consented for broad data sharing.
- Data to be collected: Our genomic study will be registered with dbGaP, and our raw whole genome sequencing data and derived data
 will be submitted to the NIMH Data Archive (NDA). Phenotypic and clinical data for all 500 research subjects will
 be collected and deposited in NDA using the data dictionaries available in NDA (described below).

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1. Recommended file formats
Explain which file format(s) should be used for this type of data and why they are appropriate for FAIR sharing and reuse.

2. Relevant tools and software
List tools, software, or platforms that can help prepare, convert, validate, organize, document, or share this type of data.

3. Recommended dataset structure or standard
State the dataset structure, schema, or community standard that should be followed, if one exists.

4. Dataset organization details
Provide detailed guidance on how the dataset should be organized, including folder structure, file naming conventions, table organization, metadata arrangement, versioning considerations, and any other important technical details.

5. Metadata and documentation files to include
List the metadata files, README files, data dictionaries, codebooks, protocols, or other documentation that should accompany the dataset.

6. Tools for metadata preparation and validation
Suggest tools that can help create, validate, manage, or standardize metadata for this dataset.

7. De-identification and privacy considerations
State whether de-identification is required. Explain what should be done based on the subject type, the data modality, and whether the study involves human participants. If consent language affects sharing, explain that clearly.

8. Recommended repositories
Suggest appropriate repositories for sharing the data, prioritizing repositories recommended, required, or commonly accepted by the funding source and data type.

9. Recommended data licenses
Recommend appropriate data license(s), prioritizing those expected, suggested, or required by the funding source. If restrictions apply because of human subjects or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as “Recommended approach” and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

ANSWER:
 Certainly! Below is practical, NIH/NIMH-tailored FAIR data guidance for your human subjects genomic study, organized by the requested sections.

---

### 1. Recommended File Formats

**Genomic Data:**
- **Raw sequencing data:** Use **FASTQ** format for raw reads; **BAM/CRAM** for aligned reads; **VCF** for variant calls. These are community standards, widely supported, and required by dbGaP and NDA.
- **Phenotypic/clinical data:** Use **CSV** or **TSV** (plain text, comma/tab-delimited) for tabular data. These formats are non-proprietary, machine-readable, and facilitate reuse.
- **Metadata and documentation:** Use **JSON**, **XML**, or **TXT** for structured metadata; **PDF** or **TXT** for protocols and README files.

### 2. Relevant Tools and Software

- **Data preparation/conversion:**
  - **SAMtools** (BAM/CRAM handling), **bcftools** (VCF), **PLINK** (genotype data), **seqtk** (FASTQ manipulation)
- **Validation:**
  - **NDA Validation Tool** (for NDA submissions), **dbGaP Submission Portal** (for dbGaP)
- **Organization/documentation:**
  - **Excel** or **Google Sheets** (for initial tabular data, export as CSV/TSV), **OpenRefine** (data cleaning)
- **Metadata management:**
  - **NDA Data Dictionary Tool**, **ISA-Tab tools** (for multi-omics metadata structuring)

### 3. Recommended Dataset Structure or Standard

- **Genomic data:** Follow **dbGaP** and **NDA** submission guidelines for file structure and metadata.
- **Phenotypic/clinical data:** Use **NDA Data Dictionary** standards, mapping variables to NDA-defined elements.
- **Metadata:** Use **NDA’s structured metadata templates** and controlled vocabularies.

### 4. Dataset Organization Details

- **Folder structure:**
  ```
  /project_root/
      /raw_data/
          /genomics/
              sample1_R1.fastq.gz
              sample1_R2.fastq.gz
              ...
          /phenotype/
              phenotypic_data.csv
      /processed_data/
          sample1.bam
          sample1.vcf
          ...
      /metadata/
          NDA_submission_manifest.csv
          data_dictionary.json
          README.txt
      /documentation/
          consent_form_template.pdf
          protocols.pdf
  ```
- **File naming conventions:**
  - Use unique, consistent IDs (e.g., `subjectID_sampleID_date.filetype`).
  - Avoid spaces/special characters; use underscores or hyphens.
- **Table organization:**
  - One row per subject/sample; columns for variables, using NDA variable names.
- **Metadata arrangement:**
  - Store metadata files in a dedicated `/metadata/` folder.
- **Versioning:**
  - Use version numbers in filenames (e.g., `phenotypic_data_v1.csv`).
  - Maintain a changelog in the README.

### 5. Metadata and Documentation Files to Include

- **README.txt:** Overview of dataset, structure, and file descriptions.
- **Data dictionary:** Define each variable, units, allowed values, and NDA mapping.
- **Submission manifest:** Required by NDA/dbGaP, listing files and metadata.
- **Consent form template:** Document participant consent for broad data sharing.
- **Protocols:** Detailed data collection and processing protocols.
- **Codebooks:** For any coded variables.
- **Data processing scripts:** If applicable, include scripts or workflow descriptions.

### 6. Tools for Metadata Preparation and Validation

- **NDA Data Dictionary Tool:** For creating and validating data dictionaries.
- **NDA Validation Tool:** Checks data and metadata compliance before submission.
- **dbGaP Submission Portal:** For metadata entry and validation.
- **ISA-Tab tools:** For multi-omics metadata structuring (if needed).

### 7. De-identification and Privacy Considerations

- **De-identification is required** for all human subjects data prior to sharing.
- **Remove all direct identifiers** (names, addresses, contact info, etc.).
- **Use NDA Global Unique Identifiers (GUIDs)** for subject IDs.
- **Genomic data:** Ensure no identifying information is embedded in file headers or metadata.
- **Consent:** Since participants are consented for broad data sharing, data can be shared via controlled-access repositories (dbGaP, NDA) in accordance with NIH policy.
- **Review NDA and dbGaP de-identification guidance** to ensure compliance.

### 8. Recommended Repositories

- **Raw and processed genomic data:**
  - **dbGaP** (Database of Genotypes and Phenotypes) – NIH-required for human genomic data.
  - **NIMH Data Archive (NDA):** Required for NIMH-funded studies; submit both genomic and phenotypic/clinical data.
- **Phenotypic/clinical data:**
  - **NIMH Data Archive (NDA):** Use NDA data dictionaries and submission tools.

### 9. Recommended Data Licenses

- **Controlled-access data:**
  - Data in dbGaP and NDA are distributed under **NIH Data Use Certification Agreements**.
  - No open license (e.g., CC-BY) is permitted for human genomic data; access is restricted to qualified researchers with approved data use requests.
- **Documentation and metadata:**
  - May be shared under **CC-BY 4.0** or similar open license, unless it contains sensitive information.

**Note:** All data sharing must comply with participant consent and NIH/NIMH policies.

---

**Summary:**
By following these recommendations, your data will be well-structured, compliant with NIH/NIMH requirements, and maximally FAIR—findable, accessible (via controlled access), interoperable, and reusable for the research community.

============================================================

--- Row 2 ---
PROMPT:
 You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to NIH, specifically targeting National Institute of Mental Health (NIMH).

Proposal context:
- Funding source: NIH
- Human subjects study: no
- Data to be collected: As detailed in the Research Strategy Section, we propose the generation of a spatially mapped single-cell atlas
 of the developing mouse brain and include specific deliverables. Our primary deliverable for each modality will be
 a matrix of cells × (counts in peaks for ATAC, UMIs in genes for RNA, or methylation status for DNAm) along with
 a dense metadata table with information for each cell. This includes the animal sex, developmental time point,
 punch of origin with x,y,z coordinates, assigned cluster and inferred cell type, assigned subcluster and inferred
 cell type, as well as a number of QC metrics (total reads, passing reads, reads in peaks, TSS enrichment, cell
 barcode combination, date of preparation for each stage, sequencing platform, likelihood of being a doublet, and
 any other relevant metrics that arise during the project).
 The amount and type of data from human cells will depend on the results from the mouse studies. Data sharing
 plans will be updated when appropriate (likely at the start of year 4 of the grant award).


# Another prompt version

In [8]:
import json
import pandas as pd

def build_prompt(row):
    funding_source = str(row.get("fundingSource", "Not provided")).strip()
    institute = str(row.get("institute", "Not provided")).strip()
    is_human = str(row.get("isHumanStudy", "No")).strip()
    consent = str(row.get("consentDescription", "")).strip()
    data_collected = str(row.get("element_1A", "Not provided")).strip()

    consent_block = ""
    if is_human.lower() in ["yes", "true", "1"]:
        consent_block = f"\n- If yes, data sharing consent: {consent if consent else 'Not provided'}"

    prompt = f"""
You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to {funding_source}, specifically targeting {institute}.

Proposal context:
- Funding source: {funding_source}
- Human subjects study: {is_human}{consent_block}
- Data to be collected: {data_collected}

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1. Recommended file formats
Explain which file format(s) should be used for this type of data and why they are appropriate for FAIR sharing and reuse.

2. Relevant tools and software
List tools, software, or platforms that can help prepare, convert, validate, organize, document, or share this type of data.

3. Recommended dataset structure or standard
State the dataset structure, schema, or community standard that should be followed, if one exists.

4. Dataset organization details
Provide detailed guidance on how the dataset should be organized, including folder structure, file naming conventions, table organization, metadata arrangement, versioning considerations, and any other important technical details.

5. Metadata and documentation files to include
List the metadata files, README files, data dictionaries, codebooks, protocols, or other documentation that should accompany the dataset.

6. Tools for metadata preparation and validation
Suggest tools that can help create, validate, manage, or standardize metadata for this dataset.

7. De-identification and privacy considerations
State whether de-identification is required. Explain what should be done based on the subject type, the data modality, and whether the study involves human participants. If consent language affects sharing, explain that clearly.

8. Recommended repositories
Suggest appropriate repositories for sharing the data, prioritizing repositories recommended, required, or commonly accepted by the funding source and data type.

9. Recommended data licenses
Recommend appropriate data license(s), prioritizing those expected, suggested, or required by the funding source. If restrictions apply because of human subjects or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as "Recommended approach" and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

Return your answer in valid JSON format only.
Do not include markdown, explanation, or extra text.

Use exactly this JSON structure:
{{
  "Recommended file formats": "",
  "Relevant tools and software": "",
  "Recommended dataset structure or standard": "",
  "Dataset organization details": "",
  "Metadata and documentation files to include": "",
  "Tools for metadata preparation and validation": "",
  "De-identification and privacy considerations": "",
  "Recommended repositories": "",
  "Recommended data licenses": ""
}}
"""
    return prompt.strip()


# Create prompt column
df["prompt"] = df.apply(build_prompt, axis=1)

# Show first prompt
print(df["prompt"].iloc[0])

You are a FAIR data expert helping researchers make their data more Findable, Accessible, Interoperable, and Reusable (FAIR).

Your task is to generate practical FAIR data instructions for a grant proposal being submitted to NIH, specifically targeting National Institute of Mental Health (NIMH).

Proposal context:
- Funding source: NIH
- Human subjects study: yes
- If yes, data sharing consent: All research participants will be consented for broad data sharing.
- Data to be collected: Demographic, clinical, and MRI, 1 H fMRS and fMRI imaging data will be acquired from 110 affected youth and 110 matched healthy controls (described in detail in sections C.3 and C.4 of this application). All data will be deidentified prior to receipt by the repository, but the information needed to generate a global unique identifier for the NIMH Data Archive (NDA) will be collected for each subject.

Based on these inputs, provide clear, practical, and user-friendly FAIR data guidance organized under the following sections:

1. Recommended file formats
Explain which file format(s) should be used for this type of data and why they are appropriate for FAIR sharing and reuse.

2. Relevant tools and software
List tools, software, or platforms that can help prepare, convert, validate, organize, document, or share this type of data.

3. Recommended dataset structure or standard
State the dataset structure, schema, or community standard that should be followed, if one exists.

4. Dataset organization details
Provide detailed guidance on how the dataset should be organized, including folder structure, file naming conventions, table organization, metadata arrangement, versioning considerations, and any other important technical details.

5. Metadata and documentation files to include
List the metadata files, README files, data dictionaries, codebooks, protocols, or other documentation that should accompany the dataset.

6. Tools for metadata preparation and validation
Suggest tools that can help create, validate, manage, or standardize metadata for this dataset.

7. De-identification and privacy considerations
State whether de-identification is required. Explain what should be done based on the subject type, the data modality, and whether the study involves human participants. If consent language affects sharing, explain that clearly.

8. Recommended repositories
Suggest appropriate repositories for sharing the data, prioritizing repositories recommended, required, or commonly accepted by the funding source and data type.

9. Recommended data licenses
Recommend appropriate data license(s), prioritizing those expected, suggested, or required by the funding source. If restrictions apply because of human subjects or consent limitations, explain that clearly.

Instructions for your response:
- Make the guidance practical, concise, and easy for researchers to follow.
- Tailor all recommendations to the combination of funding source, human-subject status, consent language, and data modality.
- When funder policies, privacy, or consent restrictions affect the answer, explain that explicitly.
- When no single standard or repository is certain, label the answer as "Recommended approach" and provide the best evidence-based guidance.
- Prefer community-accepted standards, open formats, and reusable metadata practices whenever possible.
- Keep the tone professional, helpful, and grant-writing appropriate.

Return your answer in valid JSON format only.
Do not include markdown, explanation, or extra text.

Use exactly this JSON structure:
{
  "Recommended file formats": "",
  "Relevant tools and software": "",
  "Recommended dataset structure or standard": "",
  "Dataset organization details": "",
  "Metadata and documentation files to include": "",
  "Tools for metadata preparation and validation": "",
  "De-identification and privacy considerations": "",
  "Recommended repositories": "",
  "Recommended data licenses": ""
}

In [10]:
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
client = OpenAI()

def ask_gpt(prompt_text):
    response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[
            {
                "role": "system",
                "content": "You are a FAIR data expert helping generate practical FAIR instructions."
            },
            {
                "role": "user",
                "content": prompt_text
            }
        ],
        temperature=0
    )
    return response.choices[0].message.content

# Apply to each row
df["gpt_answer"] = df["prompt"].apply(ask_gpt)

# Save output
df.to_excel("FAIR_instructions_with_prompts_and_answers2.xlsx", index=False)

In [27]:
import json
import re
import pandas as pd

def parse_json_result(text):
    empty_result = {
        "Recommended file formats": "",
        "Relevant tools and software": "",
        "Recommended dataset structure or standard": "",
        "Dataset organization details": "",
        "Metadata and documentation files to include": "",
        "Tools for metadata preparation and validation": "",
        "De-identification and privacy considerations": "",
        "Recommended repositories": "",
        "Recommended data licenses": ""
    }

    try:
        if pd.isna(text):
            return pd.Series(empty_result)

        text = str(text).strip()

        # If GPT added extra text before/after JSON, extract only the JSON part
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            text = match.group(0)

        data = json.loads(text)

        return pd.Series({
            "Recommended file formats": data.get("Recommended file formats", ""),
            "Relevant tools and software": data.get("Relevant tools and software", ""),
            "Recommended dataset structure or standard": data.get("Recommended dataset structure or standard", ""),
            "Dataset organization details": data.get("Dataset organization details", ""),
            "Metadata and documentation files to include": data.get("Metadata and documentation files to include", ""),
            "Tools for metadata preparation and validation": data.get("Tools for metadata preparation and validation", ""),
            "De-identification and privacy considerations": data.get("De-identification and privacy considerations", ""),
            "Recommended repositories": data.get("Recommended repositories", ""),
            "Recommended data licenses": data.get("Recommended data licenses", "")
        })

    except Exception:
        return pd.Series(empty_result)


# Keep only your original columns first
base_cols = [
    "link",
    "id",
    "fundingSource",
    "institute",
    "isHumanStudy",
    "consentDescription",
    "element_1A",
    "prompt",
    "gpt_answer"
]

df_base = df[base_cols].copy()

# Parse JSON from gpt_answer
parsed_cols = df_base["gpt_answer"].apply(parse_json_result)

# Combine original columns + parsed columns only once
df_clean = pd.concat([df_base, parsed_cols], axis=1)

# Preview selected columns
print(df_clean[[
    "Recommended file formats",
    "Relevant tools and software",
    "Recommended dataset structure or standard"
]].head())

# Save clean file
df_clean.to_excel("FAIR_instructions_with_parsed_columns.xlsx", index=False)

                            Recommended file formats  \
0  For MRI and fMRI imaging data, use NIfTI (.nii...
1  For raw whole genome sequencing (WGS) data, us...
2  For single-cell omics data matrices (cells × f...
3  For structural MRI data, use NIfTI (.nii or .n...

                         Relevant tools and software  \
0  Use dcm2niix for converting DICOM to NIfTI/NIf...
1  Use bcl2fastq or Illumina BaseSpace for FASTQ ...
2  Scanpy (Python), Seurat (R), AnnData (Python),...
3  Use MRI data conversion and validation tools s...

           Recommended dataset structure or standard
0  Follow the Brain Imaging Data Structure (BIDS)...
1  Follow the NIMH Data Archive (NDA) data dictio...
2  Follow the Minimum Information About a Single ...
3  Follow the Brain Imaging Data Structure (BIDS)...

In [29]:
df_clean

,link,id,fundingSource,institute,isHumanStudy,consentDescription,element_1A,prompt,gpt_answer,Recommended file formats,Relevant tools and software,Recommended dataset structure or standard,Dataset organization details,Metadata and documentation files to include,Tools for metadata preparation and validation,De-identification and privacy considerations,Recommended repositories,Recommended data licenses
0,https://grants.nih.gov/sites/default/files/flm...,1,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,"Demographic, clinical, and MRI, 1 H fMRS and f...",You are a FAIR data expert helping researchers...,"{\n ""Recommended file formats"": ""For MRI and ...","For MRI and fMRI imaging data, use NIfTI (.nii...",Use dcm2niix for converting DICOM to NIfTI/NIf...,Follow the Brain Imaging Data Structure (BIDS)...,Organize data in a BIDS-compliant folder struc...,Include a top-level README file describing the...,Use the BIDS Validator for checking BIDS compl...,De-identification is required for all human su...,Deposit all data in the NIMH Data Archive (NDA...,"For NDA, data are shared under NDA Data Use Te..."
1,https://grants.nih.gov/sites/default/files/flm...,2,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,Our genomic study will be registered with dbGa...,You are a FAIR data expert helping researchers...,"{\n ""Recommended file formats"": ""For raw whol...","For raw whole genome sequencing (WGS) data, us...",Use bcl2fastq or Illumina BaseSpace for FASTQ ...,Follow the NIMH Data Archive (NDA) data dictio...,Organize data in a hierarchical folder structu...,Include a comprehensive README.txt describing ...,Use the NDA Data Dictionary Tool and NDA Valid...,De-identification is required for all human su...,Submit raw and processed genomic data to dbGaP...,For human genomic and clinical data with broad...
2,https://grants.nih.gov/sites/default/files/flm...,3,NIH,National Institute of Mental Health (NIMH),no,no,"As detailed in the Research Strategy Section, ...",You are a FAIR data expert helping researchers...,"{\n ""Recommended file formats"": ""For single-c...",For single-cell omics data matrices (cells × f...,"Scanpy (Python), Seurat (R), AnnData (Python),...",Follow the Minimum Information About a Single ...,Organize the dataset in a top-level folder nam...,"README file describing dataset contents, struc...","MetaSRA, Annotare (EMBL-EBI), HCA Metadata Sch...",No human subjects data are included in the ini...,"For mouse single-cell omics data, deposit raw ...",Apply the Creative Commons Attribution 4.0 Int...
3,https://grants.nih.gov/sites/default/files/flm...,4,NIH,National Institute of Mental Health (NIMH),yes,All research participants will be consented fo...,The data to be shared will include MRI images ...,You are a FAIR data expert helping researchers...,"{\n ""Recommended file formats"": ""For structur...","For structural MRI data, use NIfTI (.nii or .n...",Use MRI data conversion and validation tools s...,Follow the Brain Imaging Data Structure (BIDS)...,Organize MRI data in a BIDS-compliant folder s...,"Include a README file describing the dataset, ...",Use the BIDS Validator (web or command-line) t...,De-identification is required for all shared h...,Deposit all data in the NIMH Data Archive (NDA...,"Use the NDA Data Use Certification Agreement, ..."

In [30]:
print(len(df_clean.columns))
print(df_clean.columns.tolist())

18
['link', 'id', 'fundingSource', 'institute', 'isHumanStudy', 'consentDescription', 'element_1A', 'prompt', 'gpt_answer', 'Recommended file formats', 'Relevant tools and software', 'Recommended dataset structure or standard', 'Dataset organization details', 'Metadata and documentation files to include', 'Tools for metadata preparation and validation', 'De-identification and privacy considerations', 'Recommended repositories', 'Recommended data licenses']